server:
  port: 8080
spring:
  session:
    store-type: none
  http:
     multipart:
       max-file-size: 100Mb
       max-request-size: 100Mb
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/projectdemo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: Qian123#
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  profiles:
    active: dev
mybatis:
   config-locations: classpath:mybaits/mybatis-config.xml
   mapper-locations: classpath:com/project/**/mapping/*.xml
   configuration:
     map-underscore-to-camel-case: true
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
